<?xml version="1.0"?>
<package format="3">
  <name>convex_plane_decomposition</name>
  <version>0.0.1</version>
  <description>The convex_plane_decomposition package</description>
  <maintainer email="rgrandia@ethz.ch">Ruben Grandia</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>grid_map_core</depend>
  <depend>grid_map_cv</depend>
  <depend>grid_map_filters_rsl</depend>

  <build_depend>eigen3_cmake_module</build_depend>
  <depend>libopencv-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
